version: "3"
services:     
  db:
    image: postgres
    container_name: iaep_db
    ports:
      - "5432:5432"
      - "15432:5432"
    environment:
      - POSTGRES_DB=iaep
      - PORT=5432
  server:
    build: express-server
    container_name: express-server
    environment:
      - DATABASE_URL=postgres://postgres@db/iaep
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - ./express-server:/app
    links:
      - db
    depends_on:
      - db
  client:
    build: ionic-client
    container_name: ionic-client
    ports:
      - "8100:8100"
      - "80:8100"
    environment:
      - PORT=8100
    volumes:
      - ./ionic-client:/app